### ISSUE TITLE
Raise limit of messages queued to offline device

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#378]
> I suggest to raise the limit to 100,000 messages and 100 MB. This would be enough to store a week of positions every second.

[via](https://community.owntracks.org/topic/113/off-line-1025-points-limit/2)

**Comment by ckrey** [comment]
Testing...
```
        self.session.persistence.persistent = TRUE;
        self.session.persistence.maxMessages = 100 * 1024;
        self.session.persistence.maxSize = 100 * 1024 * 1024;

```

**Comment by theorician** [comment]
Hi. Sorry to resurrect an old issue.

Could we make this user-configurable? I'd like to be able to keep a month+ of data offline. That helps for when you're in places where internet is hard to come by.

**Comment by jpmens** [comment]
I think the current limit is memory size of the device. What makes you think we're limiting the number of messages? (Related: make sure your MQTT broker will, when you get back, accept burts of messages.)

**Comment by ckrey** [comment]
No, it is limited to 100,000 entries currently (there has to be a limit).
If you are logging 1 location per second (move mode) it will be full after 27 hours
If you are logging 1 location per 5 minutes if you are moving (significant changes mode) the storage will be enough for 30+ month.

@theorician what kind of us case are you actually trying to solve?

**Comment by theorician** [comment]
@ckrey Hi. Basically my use case requires that I have a location saved every 5 seconds or 2 meters, whichever comes first (i.e. these are floors, not ceilings.) 

For comparison, using the app Pocket Earth (which I'd like to move away from since Owntracks does more) I've saved 3 months of daily movement logs at a resolution of 2s or 1m (!) and the overall GPX export size was ~350MB. The math checks out, too: A single track point in a GPX file is ~100 bytes. A day of 2s-interval points is 4MB. A month clocks in at 120MB. This is really not a lot of data.

The config variable `positions` seems to handle this. It was set at 50 by default. What's the difference between that and your hard-coded 100k offline positions? Which does what?

**Comment by ckrey** [comment]
@theorician no, the config variable `positions` does only control the number of positions recorded and displayed for each friend on the map view. This means the length of the track displayed when selecting the icon.

Offline positions are always recorded and published to the broker when it comes online again.
Offline positions are limited to 100,000 as explained above.

In iOS you need to use Move mode and set locatorInterval to 5 seconds and locatorDisplacement to 2 meters. This means a location is published every 5 seconds or when moving more than 2 meters, whichever comes first.

(GPS or Wifi positioning is not accurate to 2m)

This will only work if OwnTracks is in foreground and will consume your battery quite fast (hours) similar to a turn-by-turn navigation app. I am not sure how Pocket Earth does what you report, but if it is saving a waypoint every 5s, it will drain the battery too.
