### ISSUE TITLE
A region containing GPS *and* iBeacon info

### ISSUE THREAD

**Issue by trymbill** [owntracks/ios#407]
If I have an iBeacon in my home but I also want Owntracks to keep track of my location within my home through GPS (when my phone looses connection to the iBeacon but I'm still at home, maybe in the garden or the garage) which of the two is the correct approach?

1) Setting up one region called "-Home" with both the GPS coordinates and the iBeacon UUID
2) Setting up two regions, one called "Home" with the GPS coordinates and another called "-Home" with iBeacon UUID

Currently I'm using approach 2) with Home Assistant which treats both names as the same zone, but I'm wondering if approach 1) might be the correct one from within OwnTracks?

**Comment by ckrey** [comment]
You should use approach 1)

If the radius is > 0, OwnTracks monitors the circular  region given by the center coordinate and the radius using GPS.

If the radius is <= 0, OwnTracks monitors the iBeacon specified with UUID, major and minor.

If the radius is < 0, OwnTracks updates the coordinate everytime the iBeacon region is entered with the current GPS position. You may use this when you have "moving" iBeacons (e.g. installed in cars, suitcases, etc.)

The leading `-`as in `-Home` triggers OwnTracks to delay region leave events in order to suppress flapping iBeacon detection. Depending on your iBeacon configuration and environment this might be useful, but is not necessary.

**Comment by ckrey** [comment]
@trymbill did the last comment answer your question?

**Comment by trymbill** [comment]
Yes, thank you!
