### ISSUE TITLE
Owntracks IOS with TLS using Let's Encrypt

### ISSUE THREAD

**Issue by nilathj** [owntracks/ios#474]
Hi,
I'm trying to get the owntracks ios app working with TLS, using letsencrypt certificates on my own domain running on a PI. I have successfully got the android app working with TLS using the generated .p12 key file, connecting to my private mosquitto mqtt server on a PI.

Steps:

1. openssl pkcs12 -export -in fullchain.pem -inkey privkey.pem -name "mymosquittocert" -out mymosquittocert.p12
2. Renamed .p12 to . otrp
3. Uploaded DST Root CA X3 cert to ipad (Verified check)
4. Uploaded ISRG Root X1 cert to ipad (Verified check)
5. Uploaded Lets Encrypt Authority X3 cert to ipad (Verified check)
6. Uploaded mymqttdomain.duckdns.org cert to ipad (Verified check)
7. Uploaded mymosquittocert.otrp cert to ipad and opened with owntracks.
8. Setup private mode, with host as mymqttdomain.duckdns.org, no websockets, TLS, And selected client cert as mymosquittocert.otrp with my passphrase.
9. IPAD General->about->certificate trust settings-> Enabled Full trust for ISRG Root X1 and DST Root CA X3. (don't see any others to enable full trust)
10. NO Custom Security Policy selected. (doesn't make any difference when I select one and select allow untrusted certificates, same error)
11. Owntracks is trying to connect to: mqtts://mymqttdomain.duckdns.org:8443 c0 k69 userCJ
Gets error: 
```
error The operation couldn't be completed. (OSStatus error -9831.) {
"_KCFStreamErrorCodeKey" = "-9831";
"_KCFStreamErrorDomainKey" = 3;
}
```
Looking up this error, it means: errSSLPeerUnknownCA - An unknown certificate authority was encountered.
I'm now sure what is unknown about the CA as I've uploaded verified root certs from letsencrypt. What am I missing?

The error on mosquitto mqtt is:
```
1503144469: OpenSSL Error: error:140890B2:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:no certificate returned
1503144469: Socket error on client , disconnecting.
```
I have also deleted all the certificates from my device and only used the uploaded mymosquittocert.otrp in owntracks, but it shows the same error -9831.  I was reading, that IOS already has the LE root certs in its trust store, so no need to upload them to my device and trust them. 

I've tested my certificates successfully, so I can connect successfully to mosquitto with my certs anonymously without a username:
```
pi@hassbian:~ $ sudo mosquitto_sub -h mymqttdomain.duckdns.org -v -t \$SYS/broker/bytes/\# -p 8443 --cafile DST_Root_CA_X3.pem --cert fullchain.pem --key privkey.pem
$SYS/broker/bytes/received 223
$SYS/broker/bytes/sent 234
$SYS/broker/bytes/received 286
```

**Comment by ckrey** [comment]
you don't need an `otrp` file because 
* you don't need the sever's validation chain on the phone. It is already there for letsencrypt!
* you don't use client certificates. Please change your owntracks setup accordingly. (TLS checked but use no client certificates or custom security policy.

.* and disable mosquitto requiring client certs
![img_4635](https://user-images.githubusercontent.com/4027289/29491189-a6236050-8553-11e7-9a19-c0aa8418ee21.PNG)

**Comment by nilathj** [comment]
Thanks for the quick reply. Yes that works fine, but now anyone can access my "private" mqtt server and publish to it.  I would like to use client certificates so that only the allowed devices with the certificate can access my private mqtt server.  I don't want to use a username and pw, just client certs.

How does android work when I have require_certificate=true in mosquitto, but IOS is failing with error -9831?

**Comment by jpmens** [comment]
Your using LE certificates as client certs definitely doesn't work (as I've pointed out earlier).  Other than that, yes, using username/password (with a complex password of course) is a good design. However, since you would like to use client certs (which is more secure), why not go the whole hog and create a CA for doing that? Our Booklet describes the nitty-gritty.
