### ISSUE TITLE
Not publishing since upgrade to iOS 11.4

### ISSUE THREAD

**Issue by metbril** [owntracks/ios#542]
I have OwnTracks running in "significant changes" mode and have it running in the background without actually ever needing to open it.

Since the upgrade to iOS 11.4, I have noticed that my location is no longer being published. I need to manually publish every day or so.

This is annoying, since my [Home Assistant presence detection](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/device_tracker/owntracks.py) is based on it.

I don't mind collecting error logs if possible.

Setup:

- iPhone 6 running iOS 11.4
- OwnTracks 9.9.3
- MQTT mode
- Significant changes mode
- Publishing to CloudMQTT over Websockets port 3xxxx

**Comment by ckrey** [comment]
What do you mean by "is no longer being published" and "manually publish"?

Do the location updates queue up (badge on OwnTracks icon)?

Before you "manually publish", what is the connection status shown when pressing (i)?

**Comment by metbril** [comment]
I have switched off web sockets and things seek to be working fine for the moment

**Comment by ckrey** [comment]
Thanks for the feedback. If you switch back to web sockets, take a look at the connection status when it seems to block

**Comment by mburgholte** [comment]
I'm discovering the same issue. My setup is a little bit different to metbril. 

Setup:

- iPhone 8, iPhone 6S and iPad Air running iOS 11.4.1
- OwnTracks 9.9.3
- MQTT mode
- Significant changes mode
- Publishing to my own MQTT Broker without Websockets port 1883 and TLS.

Normally I can see under "Friends" the last time stamp of movement. Currently I can see only an actual timestamp of movement from the device I'm using. The two iPhones are sending their locations normally quit often. If I toggle the connection mode to Websockets on/off it's getting an update. But this works only manual. 
On my MQTT broker it is currently really silent. I can't see anything. I didn't change the config for a year and it worked like a charm in combination the owntracks binding in openhab 2. So maybe it's something wrong after iOS 11.4 upgrade?!

**Comment by TribuneX** [comment]
It seems that I have a related issue. Since some weeks now my owntracks app does not publish the current location to my MQTT broker (mosquitto). I can't recall when the issue actually started.

Currently I am using:

- iPhone 8 / 7 on iOS 12.1
- owntracks 9.9.3
- Significant Change mode

owntracks can successfully connect to my broker, but it does not update the location anymore. I am also using Home Assistant presence detection. When I am away, I need to open owntracks and publish my location manually. This will immedialty show up in Home Assistant. But it does not happen automatically anymore. Any ideas on how to track down this issue?

**Comment by ckrey** [comment]
@metbril @mburgholte @TribuneX how is the status of this issue? Is it solved by network setup?

**Comment by mburgholte** [comment]
@ckrey It works fine for month now. I don't know what it was. I changed nothing inside my network setup. Suddenly it was ok.
