### ISSUE TITLE
Use of iBeacons

### ISSUE THREAD

**Issue by grahamhar** [owntracks/ios#550]
Hi,

First thanks for the great app.

I am probably misunderstanding the whole point of iBeacons but there seems to be an assumption that the iBeacon is a fixed asset and needs to have a location associated with it when I add one to the app. The use case I am thinking of is if an iBeacon is located in a car, then when owntracks detects the beacon a transition event should be sent using the phones location. However, it seems to me that the location entered when the iBeacon is added to the app is used.

**Comment by ckrey** [comment]
Correct, the location associated with the beacon is transmitted in events. That's intentional.

If you use an iBeacon in a moving car or attached to a moving asset (e.g. valuable), you should set the radius to a negative value, which makes the application update the iBeacon's location on events as described here:
https://owntracks.org/booklet/features/beacons/
