### ISSUE TITLE
Why not report while position is stationary?

### ISSUE THREAD

**Issue by yabbah** [owntracks/ios#563]
Isn't there a setting in android/iOS-app that can report the position while the app know the phone remains positioning in the same place for a 5-minute period. As for now you go from A to B, but if its 750 meter between these positions it will report your position 75% between the two positions even when your positioning in position B.

Hope anyone understand what I try to say and have a solution. My automations wont work when the phones never reports as 'home' in home assistant.

**Comment by jpmens** [comment]
For this type of situation we recomend you configure a geofence which will fire when you enter or leave the location.

**Comment by yabbah** [comment]
Arena like I have to create regions in all devices. :/

**Comment by jpmens** [comment]
Right.

**Comment by yabbah** [comment]
That wasn't a solution then. I wanted the app to be re-design to send location upon stationary position.

**Comment by jpmens** [comment]
We will very gladly do that for you! Send us an email to support@owntracks.org and we will give you our hourly, daily, and monthly rates for rewriting our apps to your liking.

**Comment by yabbah** [comment]
I didn't mean you have to do it. It was a suggestion for a better experience :)

**Comment by yabbah** [comment]
> you can create regions on devices using [remoteconfig](https://owntracks.org/booklet/features/remoteconfig/)

Thanks, but this is still not what I want with this thread.

**Comment by 420Dope** [comment]
> 
> 
> Isn't there a setting in android/iOS-app that can report the position while the app know the phone remains positioning in the same place for a 5-minute period. As for now you go from A to B, but if its 750 meter between these positions it will report your position 75% between the two positions even when your positioning in position B.
> 
> Hope anyone understand what I try to say and have a solution. My automations wont work when the phones never reports as 'home' in home assistant.

This was exactly my question.
I use geofences for my home automation and it works nice. But for live logging on an map, it would be nice if the device is in a place for maybe 5 minutes and not moving, that the device sends the position once.

I don´t wand to say that you must do it, i only want to know that maybe more users find the idea useful.
Thanks for the nice app!

**Comment by ckrey** [comment]
The answer is NO due to the way iOS apps work.

You can have OwnTracks send continuous updates, just switch on Move Mode. The downside of this and has been discussed in numerous issues is the high battery drain like when you are using a turn-by-turn navigation app. We only recommend Move Mode while charging or for a short period of time.

In Significant Changes Mode the app reports when moving, or when entering/leaving a geofence or when doing a background fetch.

All these 3 updates are triggered by iOS, not by the app. There are no guarantees that the app gets triggered by iOS when moving or for background fetches when not moving (please check your Background Settings for Owntracks). Geofences work very reliable on enter and leave but obviously depend on the location detection (GPS, WLAN, Cell Tower), which again is under contol of iOS
