### ISSUE TITLE
Very high battery usage in last few days

### ISSUE THREAD

**Issue by paulfurley** [owntracks/ios#577]
Hi, thanks for making OwnTracks!

I’ve been using it for months l with background location enabled and default settings. I push locations to my own server.

On Tuesday and Wednesday afternoon I noticed my battery was unusually low by around 4pm. Digging into ios’ battery stats, I saw that owntracks had used 50% of the battery since the morning.

I’m not sure what diagnostic information to attach, let me know what’s helpful and I’ll provide it!

For now i’ve revoked background location permission to owntracks since I can’t afford the battery use, but of course that makes it a bit useless!

Thanks,
Paul

**Comment by jpmens** [comment]
Can you please tell us which device this is and which iOS version?
Also: how many regions / waypoints have you configured?

And am I right in assuming that OwnTracks is in _Significant Changes_ mode (i.e. "play" symbol) and not _Move mode_? (The latter would explain quick drainage.)

**Comment by paulfurley** [comment]
Device: iPhone 6s Plus (MKU62B/A)
iOS 12.2

I opened the app and the icon was a double right facing triangle. I think that means Move mode... 

I will try changing to Significant Changes

It’s definitely possible I hit the accidentally while viewing the app. (Now I think of it, i’ve observed family members do exactly the same thing. Seems like something that could be hidden in settings rather than on the home screen?)

**Comment by jpmens** [comment]
The double-right facing triangle is, indeed, move mode (our most precise, but it sucks the battery dry quickly, as you've experienced). Tap the icon until it shows single right-facing triangle (ie. "Play").

We put it on the main screen on purpose, so that you can, e.g. silence (i.e. put in quiet mode) when you enter a location you don't want friends to see, etc. 

We do see it happen occasionally, that people tap the symbol without realizing what's happening. We might have to think a bit more about this (feedback is welcome!), but I think putting it in settings would be too "far" away.

**Comment by paulfurley** [comment]
Thanks a lot for the quick response!

Yes I understand the rationale with the button, i’ll have a think about how it could be. Cheers!
