### ISSUE TITLE
Question: What uses most battery life, MQTT or HTTPS?

### ISSUE THREAD

**Issue by sheppy99** [owntracks/ios#617]
I've been using Owntracks for many months using MQTT together with OpenHAB, and as the Owntracks binding is being superseded in the next OH version with one based upon HTTP I wondered if there is any noticeable difference between battery usage in the 2 modes on an iphone. I primarily use it in significant changes mode with several regions.
To get around the change I've written a simple rule to take the region information from the general update over MQTT and I wonder if this is the most efficient way.

**Comment by jpmens** [comment]
I don't think any of us here have performed long-term tests on battery life differences between HTTP and MQTT, but I do know that most of us use MQTT, so that doesn't really help you.

If I myself were doing this, I too would write a small subscriber which reads MQTT and does whatever openHAB needs; I understand you've done that from withing openHAB proper which sounds sensible.

**Comment by sheppy99** [comment]
Thanks JP. it sounds like I will be sticking to MQTT!

**Comment by growse** [comment]
I'm going to take a TODO on this to do some energy profiling to see if there's any significant difference.

**Comment by ckrey** [comment]
We __know__ most of the battery is consumed by monitoring location especially if in Move mode (GPS). 
Network is only used if a location update is available and the connection is closed when in background.

We do __assume__ the type of network protocol used does not make a significant difference with regards to battery.
