### ISSUE TITLE
OwnTracks on macOS too quickly creates location pins on map

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#649]
When I hold the mouse pointer down to drag the map, OwnTracks on macOS very quickly decides I want to create a region on the map.

It would be great if either the delay before doing so could be increased, behavior were changed to do so on double-click only, or the feature were disabled completely. (I personally don't use that feature, also not when on iOS: I create a region in `Regions/` and hit `+`.)

**Comment by ckrey** [comment]
The feature should not be removed because it allows you create a region when you don't know the lat/lon coordinates: Pan and center the map on a place and then `long press`.

This is again a problem which occurs more likely if you have a simple mouse, no magic mouse or trackpad with which you can pan and zoom without pressing.

We cannot use the `double click` gesture because this is used by maps to zoom in.

The `long press` is recognized when the button is pressed longer than 0.5 seconds without moving the mouse more than 10 points (both default values).

**Comment by ckrey** [comment]
Will change the minimum duration from 0.5 to 1.5 seconds.

**Comment by ckrey** [comment]
will be changed in versions >= 13.3.8
