### ISSUE TITLE
Can a scale be added to the map?

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#721]
Would it be possible to add a scale to the map (maybe bottom right?) such as how Maps.app shows it on MacOS? If it's not too intrusive.

![rabbit-9653](https://user-images.githubusercontent.com/60706/194709164-9d93b183-3f70-428d-8c85-31461773086d.png)

**Comment by ckrey** [comment]
Can be done, but we would have to move the Modes selection to the button, because the scale appears/disappears so we cannot anchor the Modes selection below it

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-08 at 18 19 08](https://user-images.githubusercontent.com/4027289/194717435-21ef59e7-74c5-4c00-8017-ceaac6dee35a.png)

**Comment by jpmens** [comment]
No, that doesn't look good IMO; let's leave it as is, but than you for verifying.

**Comment by ckrey** [comment]
I found a way to position the scale view to the center of the bottom line. 
![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-08 at 21 41 51](https://user-images.githubusercontent.com/4027289/194724799-acaefb03-b5cb-4920-9a64-dc791ee420a2.png)

**Comment by jpmens** [comment]
That looks good.

**Comment by ckrey** [comment]
Version 16.3.2 is on its way into the App Store
