### ISSUE TITLE
Fully reset configuration when changing mode and/or host/port

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#771]
As briefly discussed internally, I suggest an enhancement which will reset our apps' configuration and internal database on change of host/port for a particular mode or on change of  mode (iOS does the latter already).

The reasoning is that if I'm hosted on a particular broker but change to a different friend's broker, say, there's no reason to keep a list of locations I've received in the past, nor is there a reason to see prior friends, as they'll likely not be on the  new broker / server.

In particular we should wipe:

- current list of friends (contacts received)
- accumulated and not yet transmitted locations (which might even be destined for an incorrect topic)

Tracked on Android at https://github.com/owntracks/android/issues/1598

**Comment by ckrey** [comment]
I think the wipe should be triggered too when
- the `userid` changes in HTTP or MQTT mode (linked to ACL)
- the `clientId` changes in MQTT mode (queues in MQTT on both ends are linked to the `clientid`)
- the `client certificates´ change in MQTT mode (not supported in HTTP mode), because this may be linked to userid/ACL
- the `url` changes in HTTP mode (may include host, port, userid, password, ...)

**Comment by ckrey** [comment]
Included in 17.2.5
