### ISSUE TITLE
Can't manually share location due to disabled map interaction

### ISSUE THREAD

**Issue by andysc** [owntracks/ios#809]
in every mode (quiet / manual / significant / move) the share icon in top right corner of map view is greyed out and can not be pressed.

I have checked that OwnTracks has permission to access my location, and it reports entry/exit from geofences correctly. I usually operate in "significant" mode.

I've never tried this before, but now I want to be able to manually publish my location sometimes, so I don't know how long this has been a problem.

**Comment by jpmens** [comment]
Is map interaction disabled? Click on the folded map icon (2nd from left on top of app) and answer the questions positively, please.

**Comment by andysc** [comment]
Thank you JP - answering yes to the questions has fixed it. In fact, just the first one is enough (do I want the map to allow interaction?).
Thank you :) You can close this now!

**Comment by jpmens** [comment]
Glad you got it sorted.

**Comment by andysc** [comment]
Thank you :)

**Comment by tmlmt** [comment]
The same thing happened to me the other day. Didn't check github and decided to reinstall the app and reconfigure my endpoint to recover the ability to manually send a location. 

I basically couldn't find out what to do at the time: it felt weird that the button was disabled even in the "Manual" mode. I would suggest (feature request) to add a tooltip in that specific case with the instructions on how to re-enable the manual button.

**Comment by andysc** [comment]
I agree - it's certainly not obvious that you have to turn on "do I want the map to allow interaction?" in order to send my current coordinates.  I consider that to be a work-around rather than what you should do to activate this feature.
Just have it active all the time - it should never be greyed out, IMHO... is there a use-case for greying it out and stopping someone reporting their location?

**Comment by jpmens** [comment]
I'm reopening this now, as it would seem we need to address this.. My recollection is that the feature was added because we had users who complained that map interaction and reverse geo lookups would be reporting their positions to Apple servers. In view of the fact users can switch to using OSM for map tiles, we might need to rethink this position?

**Comment by andysc** [comment]
So is the (continued logic) that if you want to report your location manually, but don't realise the reverse lookup is turned on, you might inadvertently give your location to Apple/whoever ? Do we need a pop up saying "geo lookup is on - are you sure? "(+ don't show me this again), to remind people it's turned on?
Or have a little icon on the map page that is a constant reminder geo lookup is turned on, and let people take responsibility for their own actions? I can see arguments several ways for this :)

**Comment by jpmens** [comment]
a popup with a reminder wouldn't do anything useful as people forget they've clicked on that; I think that's what happened to you when you clicked the folded map off? ;-)

tbh I think this is roughly the first time (two) in which somebody (inadvertently) disables interaction...

**Comment by ckrey** [comment]
OMG this is way too complicated for me and for all the users. We need less popups not more. We already have an indication that no current location is available in form of the greyed share button.

We introduced the question whether to use map interaction as a response to a user request in  #696 ... and made things more complex!

We have 2 source of location updates in the app

1. one is controlled by the modes (move, significant, manual, quiet)
2. the other is the map when map interaction is enabled

1. is not the appropriate choice for manually sharing the current location because the last location available is probably outdated if the app is not in move mode.
2. The current user location shown on the map is probably what the user wants to share, but this is only available when the map is in interactive mode.

Probably we have to introduce a 3rd location source receiving permanent location updates (as in move mode) but without invoking the backend calls as the map does ... adding more complexity.

**Comment by jpmens** [comment]
Let's please not add more complexity

**Comment by andysc** [comment]
So can we just make it so when the app knows where it is, the "send my location" button is enabled.
Just that
?

**Comment by ckrey** [comment]
This is a small change making the app know where it is, without leaking the phone's position to the map provider.

**Comment by andysc** [comment]
Could there be a "no map" option, for people who care about this?

**Comment by andysc** [comment]
just a white sheet of paper

**Comment by andysc** [comment]
(or black for night-time mode, lol!)

**Comment by jpmens** [comment]
@andysc I think it now may be time for you to begin explaining what you are actually trying to accomplish, particularly now, after all these years of being (IIRC) an actual OwnTracks for iOS user.

**Comment by ckrey** [comment]
The no-map version as I called it is the „without map interaction“ mode. You cannot zoom or pan on the map or ask the app to center on / follow on your current position. And yes, there are people caring aboit such things (#696).

In the future we will try to make OwnTracks more simple (to understand)

**Comment by andysc** [comment]
Of course - so my "for many years" use of OwnTracks has been to track my location for many years. I have geo fences for places I often go (different work offices, home, Island, etc, and that drives a display at home of "where's Andy (approximately)".

More recently, I am doing some weather-related stuff, and I need to sometimes "check in" with my location, to trigger a "weather forecast for where you are now". It's not continuous - I've already got that from OwnTracks, but just, say, if I go somewhere for a few days, I might want to move my "current location for weather forecasting purposes" to HERE rather than home.
So I need a button I can press which says "register my current location now", as I've chosen to set that as my temporary home location.

The publish now button on OwnTracks seems like the perfect solution to this :)

**Comment by ckrey** [comment]
Included in release 18.0.4

**Comment by andysc** [comment]
What is the "it" that is included in 18.0.4 ?
And.. thank you :)

**Comment by jpmens** [comment]
As per the [Changelog](https://github.com/owntracks/ios/blob/master/CHANGELOG.md):

`[NEW] keep user location available even in no-map mode #809`

**Comment by jpmens** [comment]
it is bound to show up on an App Store near you as soon as it is.
